### ISSUE TITLE
Looser dependency on thor

### ISSUE THREAD

**Issue by Dahie** [pedrozath/gambiarra#3]
Hi,

You have a strict dependency on Thor 0.2 defined in your gemspec. I'm using the the coltrane gem in a rails based project with other gems depending on Thor and particular on newer versions of it. Does Gambiarra need specifically version 0.2 or can it be opened to anything >0.2?

**Comment by pedrozath** [comment]
Taking a look now

**Comment by pedrozath** [comment]
I pushed a new version of Coltrane (4.1.1), on newest Thor and some other fixes. Please try that and see if it works.

**Comment by pedrozath** [comment]
ps: I got interested about the project. Hope it goes well :)

**Comment by Dahie** [comment]
I just update to the new version and it's working fine. Thank you!

I'm using it in https://everchords.herokuapp.com/ (https://github.com/dahie/everchords), a service I wrote to support my songwriting and have some common tools. I use coltrane for rendering a fretboard and it's music theory API may become helpful in handling song keys in the future.

You can close the issue.

**Comment by pedrozath** [comment]
Awesome @Dahie. Nice project btw!
